# app.py - WhatsApp Analyzer PRO v6 (iPhone + Android + 100% Working)
import streamlit as st
import pandas as pd
import plotly.express as px
from collections import Counter
import emoji
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import re
from datetime import datetime
import base64
from io import BytesIO

# PDF
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch

st.set_page_config(page_title="WhatsApp Analyzer PRO", page_icon="WhatsApp", layout="wide")

# CSS
st.markdown("""
<style>
    .big-font {font-size:50px !important; font-weight:bold; color:#FF6B6B;}
    .step-box {background-color:#262730; padding:20px; border-radius:12px; border-left:6px solid #FF6B6B;}
    .header {font-size:22px; color:#4ECDC4; font-weight:bold;}
</style>
""", unsafe_allow_html=True)

st.markdown('<p class="big-font">WhatsApp Chat Analyzer PRO</p>', unsafe_allow_html=True)
st.markdown("**Works with iPhone & Android exports • Made by  Nayak**")

# GUIDE
with st.expander("How to Export Chat (iPhone & Android)", expanded=True):
    st.markdown("""
    <div class="step-box">
    <p class="header">Step 1</p> Open WhatsApp → Open chat → Tap name at top<br>
    <p class="header">Step 2</p> Scroll → <strong>Export chat</strong><br>
    <p class="header">Step 3</p> Choose <strong>Without Media</strong><br>
    <p class="header">Step 4</p> Save → Upload here!
    </div>
    """, unsafe_allow_html=True)

uploaded_file = st.file_uploader("**Upload your WhatsApp chat.txt**", type="txt")

def parse_whatsapp_chat(text):
    # SUPPORTS BOTH FORMATS
    patterns = [
        # iPhone: [08/06/25, 19:48:10] Leisha: hello
        r'\[(\d{1,2}/\d{1,2}/\d{2,4}, \d{1,2}:\d{2}:\d{2})\] (.*?): (.*)',
        # Android: 08/06/25, 7:48 PM - Leisha: hello
        r'(\d{1,2}/\d{1,2}/\d{2,4}, \d{1,2}:\d{2} [APMapm]{2}) - (.*?): (.*)'
    ]
    
    dates, users, messages = [], [], []
    
    for line in text.split('\n'):
        line = line.strip()
        if not line: continue
            
        matched = False
        for pattern in patterns:
            match = re.match(pattern, line)
            if match:
                date_str, user, msg = match.groups()
                # Parse date
                for fmt in (
                    "%d/%m/%y, %H:%M:%S", "%m/%d/%y, %H:%M:%S",
                    "%d/%m/%Y, %H:%M:%S", "%m/%d/%Y, %H:%M:%S",
                    "%d/%m/%y, %I:%M %p", "%m/%d/%y, %I:%M %p"
                ):
                    try:
                        dt = datetime.strptime(date_str, fmt)
                        dates.append(dt)
                        users.append(user.strip())
                        messages.append(msg.strip())
                        matched = True
                        break
                    except:
                        continue
                if matched: break
        if matched: continue
            
        # Handle multi-line messages
        if dates and users and messages:
            messages[-1] += " " + line

    if not dates:
        return None
        
    df = pd.DataFrame({'date': dates, 'user': users, 'message': messages})
    df['date'] = pd.to_datetime(df['date'])  # ← THIS FIXES THE .dt ERROR
    df['hour'] = df['date'].dt.hour
    df['time_12h'] = df['date'].dt.strftime("%I:%M %p")
    df['day'] = df['date'].dt.day_name()
    df['date_only'] = df['date'].dt.date
    
    # Part of day
    def part(h):
        if 5 <= h < 12: return "Morning (5AM - 12PM)"
        if 12 <= h < 17: return "Afternoon (12PM - 5PM)"
        if 17 <= h < 21: return "Evening (5PM - 9PM)"
        return "Night (9PM - 5AM)"
    
    df['part_of_day'] = df['hour'].apply(part)
    df['emoji'] = df['message'].apply(lambda x: ''.join(c for c in x if c in emoji.EMOJI_DATA))
    
    return df

# PDF Generator
def create_pdf(df, figs):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1*inch)
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Center', alignment=1, fontSize=18, textColor=colors.HexColor('#FF6B6B')))
    styles.add(ParagraphStyle(name='Caption', fontSize=11, textColor=colors.grey, alignment=1))
    
    story = []
    story.append(Paragraph("WhatsApp Chat Analysis Report", styles['Title']))
    story.append(Paragraph("Generated by  Nayak", styles['Center']))
    story.append(Spacer(1, 20))
    
    # Summary
    summary = [
        ["Total Messages", f"{len(df):,}"],
        ["Participants", df['user'].nunique()],
        ["Most Active", df['user'].value_counts().iloc[0]],
        ["Duration", f"{(df['date'].max() - df['date'].min()).days} days"],
        ["Avg/Day", f"{int(len(df)/df['date_only'].nunique())}"]
    ]
    table = Table(summary, colWidths=[3*inch, 2*inch])
    table.setStyle([('GRID', (0,0), (-1,-1), 1, colors.lightgrey),
                    ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#262730')),
                    ('TEXTCOLOR', (0,0), (-1,0), colors.white)])
    story.append(table)
    story.append(Spacer(1, 30))
    
    captions = ["Top 10 Active Users", "Active Time of Day", "Peak Hours", "Top Emojis", "Word Cloud"]
    for fig, cap in zip(figs, captions):
        img_data = BytesIO()
        if hasattr(fig, 'write_image'):
            fig.write_image(img_data, format="PNG", width=1000, height=600)
        else:
            fig.savefig(img_data, format='PNG', bbox_inches='tight', dpi=150)
            plt.close()
        img_data.seek(0)
        story.append(Image(img_data, width=6.5*inch, height=4*inch))
        story.append(Paragraph(cap, styles['Caption']))
        story.append(Spacer(1, 20))
    
    doc.build(story)
    return buffer.getvalue()

# MAIN
if uploaded_file:
    raw_text = uploaded_file.read().decode("utf-8", errors="ignore")
    df = parse_whatsapp_chat(raw_text)
    
    if df is None or len(df) == 0:
        st.error("No messages found! Make sure you exported WITHOUT media.")
        st.stop()
    
    st.success(f"Analyzed {len(df):,} messages from {df['user'].nunique()} people!")

    # Metrics
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Messages", f"{len(df):,}")
    col2.metric("Most Active", df['user'].value_counts().head(1).index[0])
    col3.metric("Duration", f"{(df['date'].max()-df['date'].min()).days} days")
    col4.metric("Avg/Day", f"{int(len(df)/df['date_only'].nunique())}")

    # Charts
    st.markdown("### Top 10 Active Users")
    top10 = df['user'].value_counts().head(10)
    fig1 = px.bar(y=top10.index, x=top10.values, orientation='h', text=top10.values)
    fig1.update_traces(textposition='outside')
    st.plotly_chart(fig1, use_container_width=True)

    st.markdown("### Active Time of Day")
    part_counts = df['part_of_day'].value_counts()
    fig2 = px.pie(values=part_counts.values, names=part_counts.index)
    fig2.update_traces(textinfo='percent+label+value')
    st.plotly_chart(fig2, use_container_width=True)

    st.markdown("### Peak Hours (12-Hour)")
    hour_counts = df['time_12h'].value_counts().head(15)
    fig3 = px.bar(x=hour_counts.index, y=hour_counts.values, text=hour_counts.values)
    fig3.update_traces(textposition='outside')
    st.plotly_chart(fig3, use_container_width=True)

    st.markdown("### Word Cloud")
    text = " ".join(df['message']).lower()
    wc = WordCloud(width=1000, height=500, background_color='#0E1117', colormap='plasma',
                   stopwords={'omitted','deleted','image','video','media'}).generate(text)
    plt.figure(figsize=(12,6), facecolor='#0E1117')
    plt.imshow(wc)
    plt.axis('off')
    wordcloud_fig = plt
    st.pyplot(plt)

    st.markdown("### Top 10 Emojis")
    all_emojis = "".join(df['emoji'])
    if all_emojis:
        top_emoji = Counter(all_emojis).most_common(10)
        edf = pd.DataFrame(top_emoji, columns=['Emoji', 'Count'])
        fig4 = px.bar(edf, x='Emoji', y='Count', text='Count')
        fig4.update_traces(textposition='outside')
        st.plotly_chart(fig4, use_container_width=True)

    # PDF Button
    if st.button("Download Full Report as PDF", type="primary"):
        with st.spinner("Creating PDF..."):
            figs = [fig1, fig2, fig3, fig4, wordcloud_fig]
            pdf = create_pdf(df, figs)
            b64 = base64.b64encode(pdf).decode()
            href = f'<a href="data:application/pdf;base64,{b64}" download="WhatsApp_Report_.pdf">Download PDF Now</a>'
            st.markdown(href, unsafe_allow_html=True)
            st.balloons()
            st.success("PDF Ready!")

else:
    st.info("Upload your WhatsApp chat.txt to start")
